FROM centos:8

MAINTAINER Giuseppe Maxia <gmax@cpan.org>

RUN yum install -y libaio numactl-libs which bash-completion wget perl \
    && dnf install -y ncurses-compat-libs \
    && export USER=root \
    && export HOME=/root 

EXPOSE 3306
COPY dbdeployer /usr/bin/dbdeployer
COPY dbdeployer_completion.sh /etc/bash_completion.d/
COPY docker-entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
