FROM ubuntu

MAINTAINER Giuseppe Maxia <gmax@cpan.org>

RUN apt-get update \
    && apt-get install -y make sudo libaio1 vim-tiny perl-modules libnuma1 \
    && rm -rf /var/lib/apt/lists/* 

EXPOSE 3306
# CMD /opt/mysql/install.sh
#CMD ["mysqld"]
COPY docker-entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
